-- kategorije
insert into kategorije (id, naziv) values (1, 'Administrativna zanimanja');
insert into kategorije (id, naziv) values (2, 'Arhitektura');
insert into kategorije (id, naziv) values (3, 'Bankarstvo');
insert into kategorije (id, naziv) values (4, 'Briga o ljepoti, sport');
insert into kategorije (id, naziv) values (5, 'Dizajn i umjetnost');
insert into kategorije (id, naziv) values (28, 'Državna služba i neprofitne organizacije');
insert into kategorije (id, naziv) values (8, 'Ekonomija, financije i računovodstvo');
insert into kategorije (id, naziv) values (6, 'Elektrotehnika');
insert into kategorije (id, naziv) values (7, 'Farmaceutika i biotehnologija');
insert into kategorije (id, naziv) values (9, 'Graditeljstvo, geodezija, geologija');
insert into kategorije (id, naziv) values (10, 'Instalacije, održavanje i popravci');
insert into kategorije (id, naziv) values (11, 'IT, telekomunikacije');
insert into kategorije (id, naziv) values (12, 'Ljudski resursi');
insert into kategorije (id, naziv) values (27, 'Management');
insert into kategorije (id, naziv) values (13, 'Marketing, PR i mediji');
insert into kategorije (id, naziv) values (14, 'Obrazovanje i znanost');
insert into kategorije (id, naziv) values (15, 'Ostalo');
insert into kategorije (id, naziv) values (16, 'Poljoprivreda, šumarstvo, ribarstvo');
insert into kategorije (id, naziv) values (17, 'Pravo');
insert into kategorije (id, naziv) values (18, 'Prodaja (Trgovina)');
insert into kategorije (id, naziv) values (19, 'Proizvodnja i zanatske usluge');
insert into kategorije (id, naziv) values (20, 'Promet, transport, pomorstvo');
insert into kategorije (id, naziv) values (21, 'Sigurnost i zaštita');
insert into kategorije (id, naziv) values (22, 'Skladištenje i logistika');
insert into kategorije (id, naziv) values (23, 'Skrb (o djeci, starijima...)');
insert into kategorije (id, naziv) values (24, 'Strojarstvo i brodogradnja');
insert into kategorije (id, naziv) values (25, 'Turizam i ugostiteljstvo');
insert into kategorije (id, naziv) values (26, 'Zdravstvo, socijalni rad');
-- pojmovi
insert into pojmovi (id, kat_id, naziv) values (1, 11, 'JavaScript');
insert into pojmovi (id, kat_id, naziv) values (2, 11, 'React');
insert into pojmovi (id, kat_id, naziv) values (3, 11, 'Angular');
insert into pojmovi (id, kat_id, naziv) values (4, 11, 'Redux');
insert into pojmovi (id, kat_id, naziv) values (5, 11, 'HTML');
insert into pojmovi (id, kat_id, naziv) values (6, 11, 'CSS');
insert into pojmovi (id, kat_id, naziv) values (7, 11, 'Bootstrap');
insert into pojmovi (id, kat_id, naziv) values (8, 11, 'JSON');
insert into pojmovi (id, kat_id, naziv) values (9, 11, 'REST');
insert into pojmovi (id, kat_id, naziv) values (10, 11, 'Git');
insert into pojmovi (id, kat_id, naziv) values (11, 11, 'TypeScript');
insert into pojmovi (id, kat_id, naziv) values (12, 11, 'Java');
insert into pojmovi (id, kat_id, naziv) values (13, 11, 'Jenkins');
insert into pojmovi (id, kat_id, naziv) values (14, null, 'Big Data');
insert into pojmovi (id, kat_id, naziv) values (15, 11, 'DWH');
insert into pojmovi (id, kat_id, naziv) values (16, 11, 'Node.js');
insert into pojmovi (id, kat_id, naziv) values (17, 11, 'NodeJS');
insert into pojmovi (id, kat_id, naziv) values (18, 11, 'Vue');
insert into pojmovi (id, kat_id, naziv) values (19, 11, 'GraphQL');
insert into pojmovi (id, kat_id, naziv) values (20, 11, 'Oracle');
insert into pojmovi (id, kat_id, naziv) values (21, 11, 'MySQL');
insert into pojmovi (id, kat_id, naziv) values (22, 11, 'SQL Server');
insert into pojmovi (id, kat_id, naziv) values (23, 11, 'PostgreSQL');
insert into pojmovi (id, kat_id, naziv) values (24, 11, 'MariaDB');
insert into pojmovi (id, kat_id, naziv) values (25, 11, 'SQL');
insert into pojmovi (id, kat_id, naziv) values (26, null, 'WordPress');
insert into pojmovi (id, kat_id, naziv) values (27, null, 'CMS');
insert into pojmovi (id, kat_id, naziv) values (28, null, 'Photoshop');
insert into pojmovi (id, kat_id, naziv) values (29, null, 'Illustrator');
insert into pojmovi (id, kat_id, naziv) values (30, 11, 'Linux');
insert into pojmovi (id, kat_id, naziv) values (31, 11, 'Apache');
insert into pojmovi (id, kat_id, naziv) values (32, 11, 'PHP');
insert into pojmovi (id, kat_id, naziv) values (33, 11, 'C#');
insert into pojmovi (id, kat_id, naziv) values (34, 11, '.Net');
insert into pojmovi (id, kat_id, naziv) values (35, 11, 'Python');
insert into pojmovi (id, kat_id, naziv) values (36, 11, 'PL/SQL');
insert into pojmovi (id, kat_id, naziv) values (37, 11, 'C++');
insert into pojmovi (id, kat_id, naziv) values (38, 11, 'Android');
insert into pojmovi (id, kat_id, naziv) values (39, 11, 'iOS');
insert into pojmovi (id, kat_id, naziv) values (40, 11, 'Objective C');
insert into pojmovi (id, kat_id, naziv) values (41, 11, 'Kotlin');
insert into pojmovi (id, kat_id, naziv) values (42, 11, 'Swift');
insert into pojmovi (id, kat_id, naziv) values (43, 11, 'XCode');
insert into pojmovi (id, kat_id, naziv) values (44, 11, 'SOAP');
insert into pojmovi (id, kat_id, naziv) values (45, 11, 'API');
insert into pojmovi (id, kat_id, naziv) values (46, 11, 'jQuery');
insert into pojmovi (id, kat_id, naziv) values (47, 11, 'COBOL');
insert into pojmovi (id, kat_id, naziv) values (48, 11, 'Ruby');
insert into pojmovi (id, kat_id, naziv) values (49, 11, 'Django');
insert into pojmovi (id, kat_id, naziv) values (50, 11, 'Gradle');
insert into pojmovi (id, kat_id, naziv) values (51, 11, 'Cordova');
insert into pojmovi (id, kat_id, naziv) values (52, 11, 'Ionic');
insert into pojmovi (id, kat_id, naziv) values (53, 11, 'Maven');
insert into pojmovi (id, kat_id, naziv) values (54, 11, 'Junit');
insert into pojmovi (id, kat_id, naziv) values (55, 11, 'Eclipse');
insert into pojmovi (id, kat_id, naziv) values (56, 11, 'VMware');
insert into pojmovi (id, kat_id, naziv) values (57, 11, 'NGINX');
insert into pojmovi (id, kat_id, naziv) values (58, 11, 'DevOps');
insert into pojmovi (id, kat_id, naziv) values (59, null, 'CRM');
insert into pojmovi (id, kat_id, naziv) values (60, null, 'SAP');
insert into pojmovi (id, kat_id, naziv) values (61, null, 'ERP');
insert into pojmovi (id, kat_id, naziv) values (62, null, 'Docker');
insert into pojmovi (id, kat_id, naziv) values (63, null, 'AWS');
commit;
